#!/usr/bin/env python3
"""
Migrate Epic 7/8/9 markdown docs to canonical structure under docs/epics/*/reports,
and replace originals with an archive banner stub that links to the new canonical file.

Default: dry-run (prints planned changes). Use --apply to perform changes.

Usage:
  python3 scripts/migrate_epic_docs.py            # dry-run
  python3 scripts/migrate_epic_docs.py --apply    # perform migration
"""

import argparse
import os
import re
import sys
from pathlib import Path
from typing import List, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"

EPIC_MAP = {
    "Epic7_": "epic-07-realtime-generation",
    "Epic8_": "epic-08-effects-processing",
    "Epic9_": "epic-09-sound-design",
}

# Only migrate markdown files
def is_target_md(p: Path) -> bool:
    name = p.name
    if not name.endswith(".md"):
        return False
    # Match Epic7_/Epic8_/Epic9_ files
    for prefix in EPIC_MAP.keys():
        if name.startswith(prefix):
            return True
    return False

def find_candidates() -> List[Path]:
    candidates: List[Path] = []

    # 1) Scan docs/ top-level files
    for p in DOCS_DIR.glob("*.md"):
        if is_target_md(p):
            candidates.append(p)

    # 2) Scan repository root for root-level Epic7/8/9 markdown files
    for p in REPO_ROOT.glob("Epic[789]_*.md"):
        if is_target_md(p):
            candidates.append(p)

    # Exclude anything already inside canonical epics directories
    filtered: List[Path] = []
    for p in candidates:
        if "/docs/epics/epic-0" in str(p).replace("\\", "/"):
            continue
        filtered.append(p)

    return filtered

ARCHIVE_BANNER_TEMPLATE = """> [!IMPORTANT] Archived Document
> This file has been superseded by canonical documents in {canonical_dir}/.
> It is retained for historical reference only and should not be used for planning.

This document has been migrated to the canonical location:
- New canonical: {canonical_relpath}

Do not edit this file. Update and reference the canonical document instead.
"""

def banner_stub(canonical_dir: Path, canonical_relpath_from_orig: str) -> str:
    # canonical_dir displayed relative to repo root epics dir for clarity
    return ARCHIVE_BANNER_TEMPLATE.format(
        canonical_dir=f"docs/epics/{canonical_dir.name}",
        canonical_relpath=canonical_relpath_from_orig
    )

def compute_dest(p: Path) -> Tuple[Path, Path]:
    # Determine which epic directory to use based on filename prefix
    epic_dir_name = None
    for prefix, epic_dir in EPIC_MAP.items():
        if p.name.startswith(prefix):
            epic_dir_name = epic_dir
            break
    if not epic_dir_name:
        raise ValueError(f"Cannot determine epic destination for {p}")

    dest_dir = DOCS_DIR / "epics" / epic_dir_name / "reports"
    dest_file = dest_dir / p.name
    return dest_dir, dest_file

def ensure_dir(path: Path, apply: bool):
    if apply:
        path.mkdir(parents=True, exist_ok=True)

def relpath_from_to(src: Path, dst: Path) -> str:
    # Relative path from src file directory to dst
    return os.path.relpath(dst, start=src.parent)

def migrate_file(src: Path, apply: bool, results: List[str]) -> None:
    dest_dir, dest_file = compute_dest(src)
    ensure_dir(dest_dir, apply)

    # Compute relative canonical path for banner
    rel_to_canonical = relpath_from_to(src, dest_file)

    if not apply:
        results.append(f"[DRY-RUN] Copy {src} -> {dest_file}")
        results.append(f"[DRY-RUN] Replace {src} with archive banner pointing to {rel_to_canonical}")
        return

    # Read original content
    try:
        original = src.read_text(encoding="utf-8")
    except Exception as e:
        results.append(f"[ERROR] Failed reading {src}: {e}")
        return

    # Write canonical copy
    try:
        dest_file.write_text(original, encoding="utf-8")
        results.append(f"[OK] Wrote canonical: {dest_file}")
    except Exception as e:
        results.append(f"[ERROR] Failed writing canonical {dest_file}: {e}")
        return

    # Replace original with banner stub
    try:
        stub = banner_stub(dest_dir.parent, rel_to_canonical)
        src.write_text(stub, encoding="utf-8")
        results.append(f"[OK] Replaced original with archive banner: {src}")
    except Exception as e:
        results.append(f"[ERROR] Failed writing banner stub to {src}: {e}")

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--apply", action="store_true", help="Perform migration (default is dry-run)")
    args = parser.parse_args()

    candidates = find_candidates()
    if not candidates:
        print("No candidate markdown files found for Epic 7/8/9 migration.")
        return 0

    results: List[str] = []
    for src in sorted(candidates):
        try:
            migrate_file(src, args.apply, results)
        except Exception as e:
            results.append(f"[ERROR] {src}: {e}")

    print("\n".join(results))

    # Exit non-zero if any [ERROR]
    if any(line.startswith("[ERROR]") for line in results):
        return 2
    return 0

if __name__ == "__main__":
    sys.exit(main())
