if(EXISTS "/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_sample_engine_fileplayback[1]_tests.cmake")
  include("/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_sample_engine_fileplayback[1]_tests.cmake")
else()
  add_test(test_sample_engine_fileplayback_NOT_BUILT test_sample_engine_fileplayback_NOT_BUILT)
endif()
