if(EXISTS "/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_E2E_Simple[1]_tests.cmake")
  include("/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_E2E_Simple[1]_tests.cmake")
else()
  add_test(test_E2E_Simple_NOT_BUILT test_E2E_Simple_NOT_BUILT)
endif()
