if(EXISTS "/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_Epic9Story91[1]_tests.cmake")
  include("/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_Epic9Story91[1]_tests.cmake")
else()
  add_test(test_Epic9Story91_NOT_BUILT test_Epic9Story91_NOT_BUILT)
endif()
