if(EXISTS "/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_synth_voice[1]_tests.cmake")
  include("/Users/laurencedoby/Desktop/Development/spawn-clone/build-core/test_synth_voice[1]_tests.cmake")
else()
  add_test(test_synth_voice_NOT_BUILT test_synth_voice_NOT_BUILT)
endif()
